name: Build and Deploy Spring Boot to ECR
on:
  push:
    branches:
      - main
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Corretto 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: gha-ci-session
          aws-region: ap-northeast-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Spring Boot Application
        run: |
          cd complete
          ./gradlew clean build
      - name: Extract JAR Dependencies
        run: |
          mkdir -p build/dependency
          cd build/dependency
          pwd
          jar -xf ../libs/complete-0.0.1-SNAPSHOT.jar
      - name: Build Docker Image
        run: |
          docker build --build-arg DEPENDENCY=complete/build/dependency -t spring-boot-app:latest -f complete/Dockerfile complete/
          docker tag spring-boot-app:latest ${{ steps.login-ecr.outputs.registry }}/spring-boot-app:latest
      - name: Push Docker Image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/spring-boot-app:latest
